#!/bin/bash
cd bin
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_0.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_1.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_2.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_3.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_4.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_5.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_6.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_7.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_8.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_9.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_10.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_11.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_12.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_13.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_14.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_15.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_16.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_17.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_18.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_19.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_20.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_21.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_22.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_23.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_24.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_25.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_26.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_27.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_28.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_29.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_30.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_31.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_32.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_33.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_34.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_35.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_36.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_37.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_38.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_39.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_40.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_41.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_42.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_43.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_44.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_45.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_46.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_47.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_48.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_49.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_50.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_51.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_52.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_53.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_54.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_55.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_56.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_57.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_58.txt Red
java PuzzleClient.PuzzleSolverClient /Users/giacomomanzoli/repos/PP3/P3_parte3/test/test9.txt /Users/giacomomanzoli/repos/PP3/P3_parte3/test/soluzione9_59.txt Red
cd ..

